config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # 下面這行，把註冊的預設網址改成http://localhost:3000/lab515/sign_up，一樣上線版要改成不同的網址
    get "/lab515/sign_up" => "devise/registrations#new", as: "new_user_registration"
    get "/lab515/sign_in" => "devise/sessions#new"

    get "/users/sign_up"  => redirect('/')     # 關掉devise原始路由設定
    get "/users/sign_in"  => redirect('/')
    get "/users/graduates"=> "users#graduates" # 顯示已畢業的實驗室成員
  end
                                 # 第一層：發表文章、編輯文章
  resources :notes               # 學習資源
  resources :posts               # 榮譽榜
  resources :professorworks      # 教授的著作

  devise_for :users, :controllers => {registrations: "users/registrations",
                                      omniauth_callbacks: "users/omniauth_callbacks"  }

  resources :users, only: [:index, :show]      # 開啟users的index, show頁面
                                 # 登入系統，實驗室成員資料，只能登入不能註冊
  devise_for :managers

  root 'welcome#index'           # 首頁

  namespace :dashboard do        # 第二層：~~上線版要把dashboard改名，不能讓非實驗室成員能進入這頁面~~，
                                 #          其實只要before_action :authenticate_user!即可
                                 #          查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    resources :notes
    resources :posts
    resources :users             # 實驗室成員：編輯個資
                                 #           查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    put 'api/image_upload' => 'api#image_upload', as: :image_upload
                                 # AJAX 上傳個人大頭照圖片


    namespace :admin do          # 第三層：上線的版本要把admin改成亂碼
      resources :managers        # 網站管理員
      resources :users           # 刪除實驗室成員的權限
      resources :professorworks  # 教授的著作
    end
  end

  # get '*path' => redirect('/')   #錯誤的路由，都會被導到首頁
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :user_id

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def slug_candidates
    [
      :title,
      [:title, :created_at]
    ]
  end

  # 作者有權限編輯
  def is_written_by?(user)
    user && user == author
  end
end

app/controllers/dashboard/notes_controller.rb
class Dashboard::NotesController < Dashboard::DashboardController
  before_action :authenticate_user!
  before_action :find_note, only: [:edit, :update]

  def new
    @note = current_user.notes.new
  end

  def create
    @note = current_user.notes.create(note_params)

    if @note.save
      redirect_to @note
    else
      render `new`
    end
  end

  def edit

  end

  def update

    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note = current_user.notes.friendly.find(params[:id])
    @note.destroy

    redirect_to notes_path
  end

  private

  def note_params
    params.require(:note).permit(:author, :title, :content, :is_editable,
                                 :link_text, :link_site)
  end

  def find_note
    @note = Note.friendly.find(params[:id])
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all.order("created_at asc").paginate(page: params[:page], per_page:3)
  end

  def show
    @note = Note.friendly.find(params[:id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/index.html.erb
<h1 id="page_title">Learning Resources</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <div class="post">
    <% @notes.each do |note| %>

        <h2><%= link_to note.title, note %></h2>
        <p class="date"><%= note.created_at.strftime('%b %d, %Y') %></p>
        <hr>

    <% end %>

    <% if user_signed_in? %>
      <%= link_to "new note", new_dashboard_note_path, class: "view_more" %>
    <% end %>
  </div>
</div>

<%= will_paginate @posts %>

app/views/notes/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">

  <header>
    <h1><%= @note.title %></h1>
    <p class="date"><%= @note.created_at.strftime('%A, %B %d') %></p>
    <p><%= @note.author.fb_name %></p>

    <hr>
  </header>

  <div id="content">
    <%= markdown @note.content %>
  </div>

  <br>

  <!-- <% if @note.link_text.present? && @note.link_site.present? %>
    <%= link_to @note.link_text, @note.link_site, class: "view_more" %>

    <br>

    <br>

    <br>

  <% end %> -->

  <div class="wrapper about homepage_content">
    <!-- <hr> -->
    <header class="clearfix">

      <% if @note.link_text.present? && @note.link_site.present? %>
        <h2><%= link_to @note.link_text, @note.link_site, class: "view_more", target: "_blank" %></h2>
      <% end %>

    </header>
    <!-- <hr> -->
  </div>

  <!-- 作者自己可以編輯 OR 開放給其他實驗室成員都能編輯  -->
  <% if @note.is_written_by?(current_user) || (user_signed_in? && @note.is_editable) %>
    <%= link_to "Edit", edit_dashboard_note_path, class: "view_more" %>
  <% end %>

  <!-- 作者自己可以刪除 -->
  <% if @note.is_written_by?(current_user) %>
    <%= link_to "Delete", dashboard_note_path, class: "view_more",
                                               method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>

</div>