config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # 下面這行，把註冊的預設網址改成http://localhost:3000/lab515/sign_up，一樣上線版要改成不同的網址
    get "/lab515/sign_up" => "devise/registrations#new", as: "new_user_registration"
    get "/lab515/sign_in" => "devise/sessions#new"

    get "/users/sign_up"  => redirect('/')     # 關掉devise原始路由設定
    get "/users/sign_in"  => redirect('/')
    get "/users/graduates"=> "users#graduates" # 顯示已畢業的實驗室成員
  end
                                 # 第一層：發表文章、編輯文章
  resources :notes               # 學習資源
  resources :posts               # 榮譽榜
  resources :professorworks      # 教授的著作

  devise_for :users, :controllers => {registrations: "users/registrations",
                                      omniauth_callbacks: "users/omniauth_callbacks"  }

  resources :users, only: [:index, :show]      # 開啟users的index, show頁面
                                 # 登入系統，實驗室成員資料，只能登入不能註冊
  devise_for :managers

  root 'welcome#index'           # 首頁

  namespace :dashboard do        # 第二層：~~上線版要把dashboard改名，不能讓非實驗室成員能進入這頁面~~，
                                 #          其實只要before_action :authenticate_user!即可
                                 #          查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    resources :notes
    resources :posts
    resources :users             # 實驗室成員：編輯個資
                                 #           查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    put 'api/image_upload' => 'api#image_upload', as: :image_upload
                                 # AJAX 上傳個人大頭照圖片


    namespace :admin do          # 第三層：上線的版本要把admin改成亂碼
      resources :managers        # 網站管理員
      resources :users           # 刪除實驗室成員的權限
      resources :professorworks  # 教授的著作
    end
  end

  # get '*path' => redirect('/')   #錯誤的路由，都會被導到首頁
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  # 給user index 頁面撈「不同學位」的實驗室成員
  scope :doctor,        -> { where(:academic_degree => 'Ph.D') }
  scope :master,        -> { where(:academic_degree => 'master') }
  scope :college,       -> { where(:academic_degree => 'college') }
  scope :has_graduated, ->(status) { where( has_graduated: status) }

  has_many :posts
  has_many :post_authorities
  has_many :editable_posts, through: :post_authorities, source: :post

  has_many :notes
  has_many :images # 上傳個人大頭貼

  # 撈user最後一張上傳的圖片，用於user index view
  def last_image
    images.last
  end

  #臉書登入
  def self.from_omniauth(auth)

    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
       user.fb_token = auth.credentials.token

       user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.fb_name = auth.info.name
      existing_user.fb_image = auth.info.image

      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.fb_name = auth.info.name
    user.fb_image = auth.info.image

    user.save!
    return user
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::DashboardController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:taiwan_name, :english_name, :paper, :profile,
                                 :has_graduated, :academic_degree,
                                 :joined_CYCU_at_which_year, :has_spent_how_much_time_at_CYCU)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication  # 這邊是可以客制的
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    stored_location_for(resource) || current_user
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def index
    @users_doctor = User.includes(:images).doctor.has_graduated(false).order(joined_CYCU_at_which_year: :desc)
    @users_master = User.includes(:images).master.has_graduated(false).order(joined_CYCU_at_which_year: :desc)
    @users_college = User.includes(:images).college.has_graduated(false).order(joined_CYCU_at_which_year: :desc)
  end

  def show
    @image = @user.images.last
  end

  def graduates
    @users_doctor = User.includes(:images).doctor.has_graduated(true).order(joined_CYCU_at_which_year: :asc)
    @users_master = User.includes(:images).master.has_graduated(true).order(joined_CYCU_at_which_year: :asc)
    @users_college = User.includes(:images).college.has_graduated(true).order(joined_CYCU_at_which_year: :asc)
  end

  def find_user
    @user = User.includes(:images).find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/graduates.html.erb
<!-- <h1>This is graduates action</h1>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">

  <h1>博士生</h1>
  <% @users_doctor.each do |user_doctor| %>
    <%= link_to user_doctor.taiwan_name, user_doctor %>
  <% end %>

  <hr>

  <h1>研究生</h1>
  <% @users_master.each do |user_master| %>
    <%= link_to user_master.taiwan_name, user_master %>
  <% end %>

  <hr>

  <h1>大學生</h1>
  <% @users_college.each do |user_college| %>
    <%= link_to user_college.taiwan_name, user_college %>
  <% end %>

  <hr>


</div> -->


<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <h1>畢業生</h1>
  </header>

  <h1>博士生</h1>
  <div class="row clearfix">
    <% @users_doctor.each do |doctor_user| %>
      <div class="lab_member">
        <% if doctor_user.last_image.present? %>
          <%= link_to image_tag(doctor_user.last_image.image.url(:icon)), doctor_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to doctor_user.taiwan_name, doctor_user %></p>
        <p class="year"><%= doctor_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>

  <hr>

  <h1>研究生</h1>
  <div class="row clearfix">
    <% @users_master.each do |master_user| %>
      <div class="lab_member">
        <% if master_user.last_image.present? %>
          <%= link_to image_tag(master_user.last_image.image.url(:icon)), master_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to master_user.taiwan_name, master_user %></p>
        <p class="year"><%= master_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>

  <hr>

  <h1>大學生</h1>
  <div class="row clearfix">
    <% @users_college.each do |college_user| %>
      <div class="lab_member">
        <% if college_user.last_image.present? %>
          <!-- <%= image_tag college_user.last_image.image.url(:icon) %> -->
          <%= link_to image_tag(college_user.last_image.image.url(:icon)), college_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to college_user.taiwan_name, college_user %></p>
        <p class="year"><%= college_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>


  <section id="graduation" class="clearfix">
    <div class="wrapper about homepage_content">
      <hr>
      <header class="clearfix">
        <h2><%= link_to "還在學校的實驗室成員", users_path, class: "view_more" %></h2>
      </header>
      <hr>
    </div>
  </section>



</div>


<!-- <%= link_to "還在學校的實驗室成員", users_path, class: "view_more" %> -->

app/views/users/index.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <h1>Lab Members</h1>
  </header>

  <h1>博士生</h1>
  <div class="row clearfix">
    <% @users_doctor.each do |doctor_user| %>
      <div class="lab_member">
        <% if doctor_user.last_image.present? %>
          <%= link_to image_tag(doctor_user.last_image.image.url(:icon)), doctor_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to doctor_user.taiwan_name, doctor_user %></p>
        <p class="year"><%= doctor_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>

  <hr>

  <h1>研究生</h1>
  <div class="row clearfix">
    <% @users_master.each do |master_user| %>
      <div class="lab_member">
        <% if master_user.last_image.present? %>
          <%= link_to image_tag(master_user.last_image.image.url(:icon)), master_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to master_user.taiwan_name, master_user %></p>
        <p class="year"><%= master_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>

  <hr>

  <h1>大學生</h1>
  <div class="row clearfix">
    <% @users_college.each do |college_user| %>
      <div class="lab_member">
        <% if college_user.last_image.present? %>
          <!-- <%= image_tag college_user.last_image.image.url(:icon) %> -->
          <%= link_to image_tag(college_user.last_image.image.url(:icon)), college_user %>
        <% else %>
          <%= image_tag asset_path 'images/missing.jpg' %>
        <% end %>
        <p class="name"><%= link_to college_user.taiwan_name, college_user %></p>
        <p class="year"><%= college_user.joined_CYCU_at_which_year %>學年</p>
      </div>
    <% end %>
  </div>


  <section id="graduation" class="clearfix">
    <div class="wrapper about homepage_content">
      <hr>
      <header class="clearfix">
        <h2><%= link_to "已畢業的實驗室成員", users_graduates_path, class: "view_more" %></h2>
      </header>
      <hr>
    </div>
  </section>



</div>

app/views/users/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <h1><%= @user.english_name %> (<%= @user.taiwan_name %>)</h1>
    <p class="date">入學學年：<%= @user.joined_CYCU_at_which_year %>學年</p>
    <hr>
  </header>

  <div id="content">
    <div id="personal_img">
      <% if @image.present? %>
        <%= image_tag @image.image.url %>
      <% end %>
    </div>

    <br>
    <br>
    <br>

    <h1>Introdce Myself</h1>

    <br>

    <%= markdown @user.profile unless @user.profile.nil? %>

    <br>

    <h1>Papers</h1>

    <br>

    <%= markdown @user.paper unless @user.profile.nil? %>

    <br>

    <% if current_user == @user %>
      <div id="admin_links">
        <%= link_to "edit profile", edit_dashboard_user_path, class: "view_more" %>
      </div>
    <% end %>

  </div>
</div>