config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # 下面這行，把註冊的預設網址改成http://localhost:3000/lab515/sign_up，一樣上線版要改成不同的網址
    get "/lab515/sign_up" => "devise/registrations#new", as: "new_user_registration"
    get "/lab515/sign_in" => "devise/sessions#new"

    get "/users/sign_up"  => redirect('/')     # 關掉devise原始路由設定
    get "/users/sign_in"  => redirect('/')
    get "/users/graduates"=> "users#graduates" # 顯示已畢業的實驗室成員
  end
                                 # 第一層：發表文章、編輯文章
  resources :notes               # 學習資源
  resources :posts               # 榮譽榜
  resources :professorworks      # 教授的著作

  devise_for :users, :controllers => {registrations: "users/registrations",
                                      omniauth_callbacks: "users/omniauth_callbacks"  }

  resources :users, only: [:index, :show]      # 開啟users的index, show頁面
                                 # 登入系統，實驗室成員資料，只能登入不能註冊
  devise_for :managers

  root 'welcome#index'           # 首頁

  namespace :dashboard do        # 第二層：~~上線版要把dashboard改名，不能讓非實驗室成員能進入這頁面~~，
                                 #          其實只要before_action :authenticate_user!即可
                                 #          查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    resources :notes
    resources :posts
    resources :users             # 實驗室成員：編輯個資
                                 #           查看該帳號發表過什麼文章，點選文章後進入第一層觀看文章，並且編輯之

    put 'api/image_upload' => 'api#image_upload', as: :image_upload
                                 # AJAX 上傳個人大頭照圖片


    namespace :admin do          # 第三層：上線的版本要把admin改成亂碼
      resources :managers        # 網站管理員
      resources :users           # 刪除實驗室成員的權限
      resources :professorworks  # 教授的著作
    end
  end

  # get '*path' => redirect('/')   #錯誤的路由，都會被導到首頁
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true

  belongs_to :author, class_name: "User", foreign_key: :user_id
  # delegate :email, :to => :author


  has_many :post_authorities                                    # post 與 user 的中介表
  has_many :editors, through: :post_authorities, source: :user  # 多對多

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def slug_candidates
    [
      :title,
      [:title, :created_at]
    ]
  end

  ### 定義在model裡的method可以在view裡使用

  # 作者有權限編輯
  def is_written_by?(user)
    user && user == author
  end

  # 授權的人能夠編輯
  def is_authorized_to_edit_by?(user)
    post_authorities.where(user_id: user.id).present?
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::DashboardController
  before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update]

  def new
    @post = current_user.posts.build
    @post_authorities = @post.post_authorities.build
    @users_still_in_college = User.all.has_graduated(false)
  end

  def create
    @post = current_user.posts.build(post_params)
    @users_still_in_college = User.all.has_graduated(false)

    # 把user_id、post_id存入中介表
    params[:editors][:id].each do |editor|
      if !editor.empty?
        @post.post_authorities.build(:user_id => editor)
      end
    end


    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post_authorities = @post.post_authorities.build
    @users_still_in_college = User.all.has_graduated(false)
  end

  def update

    if @post.update(post_params)
        @post.editors = []
        params[:editors][:id].each do |editor|
          if !editor.empty?
            @post.editors << User.find(editor)
          end
        end
      redirect_to @post
    else
      render 'edit'
    end

  end

  def destroy
    @post = current_user.posts.friendly.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end


  private

  def find_post
    @post = Post.friendly.find(params[:id])
    # @post = current_user.posts.find(params[:id])  #高見龍建議寫法，但是不能全部都work
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id,
                                  post_authorities_attributes: [:id, :post_id, :user_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.all.order("created_at desc").paginate(page: params[:page], per_page:3)
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1 id="page_title">BULLETIN BOARD</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <div class="post">
    <% @posts.each do |post| %>

        <h2><%= link_to post.title, post %></h2>
        <p class="date"><%= post.created_at.strftime('%b %d, %Y') %></p>
        <hr>

    <% end %>

    <% if user_signed_in? %>
      <%= link_to "new post", new_dashboard_post_path, class: "view_more" %>
    <% end %>
  </div>
</div>

<%= will_paginate @posts %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">

  <header>
    <h1><%= @post.title %></h1>
    <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <p><%= @post.author.fb_name %></p>

    <hr>
  </header>

  <div id="content">
    <%= markdown @post.content %>
  </div>

  <br>



  <!-- 作者自己可以編輯 -->
  <% if @post.is_written_by?(current_user)   %>
    <%= link_to "Edit", edit_dashboard_post_path, class: "view_more" %>
    <%= link_to "Delete", dashboard_post_path, class: "view_more",
                                               method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>

  <!-- 被授權的文章編輯者 -->
  <% if user_signed_in? && @post.is_authorized_to_edit_by?(current_user)  %>
    <%= link_to "授權編輯Edit", edit_dashboard_post_path, class: "view_more" %>
  <% end %>





</div>